# Generated by Django 3.2.5 on 2024-05-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0002_auto_20220525_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Airline_name',
            field=models.CharField(choices=[('EGA', 'Egypt Air'), ('NIA', 'Pobeda'), ('ARA', 'Arabic Air')], default='Pobeda', max_length=15),
        ),
        migrations.AlterField(
            model_name='flights',
            name='From',
            field=models.CharField(choices=[('CAI', 'Moscow Airport'), ('HGR', ' Hurghada Airport'), ('HBE', 'Borg El Arab Airport'), ('SSH', 'Kazan Airport')], default='Moscow Airport', max_length=30),
        ),
        migrations.AlterField(
            model_name='flights',
            name='To',
            field=models.CharField(choices=[('CAI', 'Moscow Airport'), ('HGR', ' Hurghada Airport'), ('HBE', 'Borg El Arab Airport'), ('SSH', 'Kazan Airport')], default='Borg El Arab Airport', max_length=30),
        ),
    ]
